### ISSUE TITLE
Link to this repo from github.com/hallgren/eventsourcing

### ISSUE THREAD

**Issue by hallgren** [kieranajp/event-sourcing-tech-talk#1]
Hi @kieranajp, I'm working on improving the examples in the eventsourcing repo and stumbled on your repo. Would it be okey if I link to your project from https://github.com/hallgren/eventsourcing/

BR Morgan

**Comment by kieranajp** [comment]
Hey Morgan, thanks for reaching out! Yes, no problem at all.

BTW, you might be interested to hear that after I gave the internal tech talk that this repo was created for, we decided to use your library for some of our production systems too :)

**Comment by hallgren** [comment]
> Hey Morgan, thanks for reaching out! Yes, no problem at all.

Thanks!

> BTW, you might be interested to hear that after I gave the internal tech talk that this repo was created for, we decided to use your library for some of our production systems too :)

I would like to be a fly on that internal tech talk wall :)

It would be interesting to know what problems you are going to solve with the lib and if you have some feedback on how the lib is constructed.

**Comment by kieranajp** [comment]
Without going too much into specifics, we have a particular workflow that relies heavily on external parties, and when something goes wrong it's hard to see the chain of events that led to the current state. So naturally ES is the right fit for it. 

Personally the thing I'd like to see in the lib moving forward would be official support for projections or at least a recommended pattern that can be used to build them - while it's of course possible to build them using the tools provided today, there's a number of different ways it could be done, and it would be better to have some uniformity around them.

**Comment by hallgren** [comment]
There's an ongoing [draft](https://github.com/hallgren/eventsourcing/pull/104) that explore projections. I would be perfect if you could have a look to see if it fit your needs.

**Comment by hallgren** [comment]
The projections PR is now merged.
